# Generated by Django 5.2.3 on 2025-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operator',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
    ]
