# Generated by Django 5.2.3 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bus_del_flag_alter_operator_del_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('VIP', 'VIP')], max_length=10),
        ),
    ]
