# Generated by Django 5.2.3 on 2025-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_created_at_feedback_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.IntegerField(default=0),
        ),
    ]
