# Generated by Django 5.2.3 on 2025-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
