# Generated by Django 5.2.3 on 2025-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_questionandanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_date'], 'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedback'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1 Star (Very Poor)'), (2, '2 Stars (Poor)'), (3, '3 Stars (Average)'), (4, '4 Stars (Good)'), (5, '5 Stars (Excellent)')], default=3, help_text='Overall rating of the experience.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Detailed feedback message.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, help_text='Admin response to the feedback.', null=True),
        ),
    ]
